name: docker

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "dckr_pat_GMz0KbYNJWPV3fl8ejNjt8xS5pU" | docker login -u "Kayan2005 " --password-stdin

      - name: Build Docker image
        run: docker build -t faizaben/vote-app:$GITHUB_SHA -t faizaben/vote-app:latest .

      - name: Push Docker image
        run: |
          docker push faizaben/vote-app:$GITHUB_SHA
          docker push faizaben/vote-app:latest
